"""
DataVault — Airflow DAG
=======================

Daily orchestration of the DataVault dbt pipeline.

Schedule: 06:00 UTC daily
Trigger:  Automatic (daily) or manual via the Airflow UI

Task dependency chain:
    dbt_seed
        → dbt_snapshot
            → dbt_build_staging
                → dbt_build_intermediate
                    → dbt_build_marts
                        → dbt_test_singular

Each task is a BashOperator running a scoped dbt command inside the project
directory mounted at /opt/datavault inside the Docker container.

Failure behaviour:
    - Each task retries once after 5 minutes
    - On failure, a Slack notification is posted via the 'datavault_slack'
      Airflow connection (HTTP connection with Slack Incoming Webhook URL)
    - See SLACK_SETUP.md for full configuration instructions

Prerequisites:
    1. Docker Compose stack running (make airflow-up)
    2. Python + dbt installed inside the Airflow Docker image, or use
       a DockerOperator / KubernetesPodOperator in production
    3. datavault_slack Airflow connection configured (see SLACK_SETUP.md)
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from typing import Any, Callable

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.providers.http.hooks.http import HttpHook

# ── Constants ─────────────────────────────────────────────────────────────────
# The DataVault project is mounted at /opt/datavault inside the container.
# The BashOperators cd to this directory before running dbt.
PROJECT_DIR = os.environ.get("DATAVAULT_PROJECT_DIR", "/opt/datavault")

# Reusable dbt command prefix — always pass --profiles-dir so dbt finds
# profiles.yml inside the project root rather than ~/.dbt/
DBT_CMD = f"cd {PROJECT_DIR} && dbt"
PROFILES_FLAG = "--profiles-dir ."

# ── Slack failure callback ─────────────────────────────────────────────────────

def send_slack_failure_alert(context: dict[str, Any]) -> None:
    """
    Post a Slack notification when a task fails.

    Reads the webhook URL from the 'datavault_slack' Airflow connection:
        Conn Type : HTTP
        Password  : https://hooks.slack.com/services/your/webhook/url

    To configure this connection:
        1. Open Airflow at http://localhost:8080
        2. Admin → Connections → Add connection
        3. Conn Id: datavault_slack
           Conn Type: HTTP
           Password: <your Slack webhook URL>
        See SLACK_SETUP.md for a complete step-by-step guide.
    """
    try:
        hook = HttpHook(method="POST", http_conn_id="datavault_slack")

        task_instance = context.get("task_instance")
        dag_id = context.get("dag").dag_id
        task_id = task_instance.task_id if task_instance else "unknown"
        execution_date = context.get("execution_date", "unknown")
        log_url = (
            task_instance.log_url
            if task_instance
            else "https://airflow.local/log"
        )

        payload = {
            "text": (
                f":red_circle: *DataVault pipeline failure*\n"
                f"*DAG:*   `{dag_id}`\n"
                f"*Task:*  `{task_id}`\n"
                f"*Run:*   `{execution_date}`\n"
                f"<{log_url}|View task logs>"
            )
        }

        hook.run(
            endpoint="",  # Webhook URL is the base URL on the connection
            data=json.dumps(payload),
            headers={"Content-Type": "application/json"},
        )

    except Exception as exc:  # noqa: BLE001
        # Never let the callback itself crash the task — just log and move on
        print(f"[datavault_slack] Failed to send Slack alert: {exc}")


# ── Default task arguments ────────────────────────────────────────────────────

default_args: dict[str, Any] = {
    "owner": "datavault",
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
    "on_failure_callback": send_slack_failure_alert,
}

# ── DAG definition ────────────────────────────────────────────────────────────

with DAG(
    dag_id="datavault_pipeline",
    description=(
        "Daily DataVault dbt pipeline: seed → snapshot → staging → "
        "intermediate → marts → singular tests"
    ),
    default_args=default_args,
    schedule_interval="0 6 * * *",   # 06:00 UTC daily
    start_date=datetime(2024, 1, 1),
    catchup=False,                    # Don't backfill historical runs
    max_active_runs=1,                # Only one run at a time
    tags=["datavault", "dbt", "motor-insurance"],
    doc_md=__doc__,
) as dag:

    # ── Task 1: Load seed data ─────────────────────────────────────────────────
    # Seeds are the raw CSV files generated by scripts/generate_data.py.
    # In production, this task would be replaced by an ingestion layer trigger.
    t_seed = BashOperator(
        task_id="dbt_seed",
        bash_command=f"{DBT_CMD} seed {PROFILES_FLAG}",
        doc_md=(
            "Load raw seed CSV files (raw_customers, raw_policies, raw_claims) "
            "into the DuckDB 'raw' schema. In production, replace with an "
            "ingestion layer trigger (Fivetran, Airbyte, etc.)."
        ),
    )

    # ── Task 2: SCD snapshots ─────────────────────────────────────────────────
    # Runs both snapshots: scd_customers (Type 1) and scd_policies (Type 2).
    # Must run AFTER seed so the source data is current.
    t_snapshot = BashOperator(
        task_id="dbt_snapshot",
        bash_command=f"{DBT_CMD} snapshot {PROFILES_FLAG}",
        doc_md=(
            "Run SCD snapshots. "
            "scd_customers: Type 1 (check strategy, overwrites on address/phone change). "
            "scd_policies: Type 2 (timestamp strategy, preserves premium history)."
        ),
    )

    # ── Task 3: Build staging (bronze) ────────────────────────────────────────
    # Views only — fast to build. Includes generic schema tests from dbt build.
    t_build_staging = BashOperator(
        task_id="dbt_build_staging",
        bash_command=f"{DBT_CMD} build --select staging {PROFILES_FLAG}",
        doc_md=(
            "Build and test bronze staging views: stg_customers, stg_policies, "
            "stg_claims. Runs all generic schema tests (not_null, unique, "
            "relationships, accepted_values, dbt_expectations)."
        ),
    )

    # ── Task 4: Build intermediate (silver) ──────────────────────────────────
    # Tables with business logic. Depends on staging being clean.
    t_build_intermediate = BashOperator(
        task_id="dbt_build_intermediate",
        bash_command=f"{DBT_CMD} build --select intermediate {PROFILES_FLAG}",
        doc_md=(
            "Build and test silver intermediate tables: int_policy_claims_bridge, "
            "int_customer_risk_profile. Applies the risk_band macro and aggregates "
            "lifetime claim metrics."
        ),
    )

    # ── Task 5: Build marts (gold) ────────────────────────────────────────────
    # Contract-enforced tables. Build failure here means schema drift detected.
    t_build_marts = BashOperator(
        task_id="dbt_build_marts",
        bash_command=f"{DBT_CMD} build --select marts {PROFILES_FLAG}",
        doc_md=(
            "Build and test gold mart tables with enforced dbt contracts: "
            "mart_customer_risk, mart_claims_summary, mart_policy_renewals. "
            "A build failure here means schema drift has been detected — "
            "a column has been renamed, removed, or changed type."
        ),
    )

    # ── Task 6: Singular tests ────────────────────────────────────────────────
    # Run custom business-logic tests last, after all models are built.
    t_test_singular = BashOperator(
        task_id="dbt_test_singular",
        bash_command=(
            f"{DBT_CMD} test --select test_type:singular {PROFILES_FLAG}"
        ),
        doc_md=(
            "Run custom singular tests: "
            "assert_no_overlapping_scd_policy_dates (SCD Type 2 integrity), "
            "assert_claim_amount_within_vehicle_value (business rule validation)."
        ),
    )

    # ── Task dependency chain ─────────────────────────────────────────────────
    # A failure in any upstream task stops all downstream tasks.
    # Airflow retries each task once after 5 minutes before alerting.
    (
        t_seed
        >> t_snapshot
        >> t_build_staging
        >> t_build_intermediate
        >> t_build_marts
        >> t_test_singular
    )
